### ISSUE TITLE
 I hope to get your help

### ISSUE THREAD

**Issue by MrHanbing** [Marm0t/dji-phantom3-parser#1]
May I ask about the analysis of DJI log,and  the data format?Has the document been updated recently？ I hope to get your help！
 thank you

**Comment by Marm0t** [comment]
Hello,

Unfortunately this project was abandoned about 2 years ago and for now there are no plans to continue. I'm afraid that for last 2 year DJI could change a lot their protocols and data format, even though there is a fat chance that some structures described here could still be the same.

My apologies.
